FROM node:18.20.5 as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

CMD [ "node", ".output/server/index.mjs" ]

FROM nginx:stable-alpine as production-stage

COPY --from=build /app/dist /usr/share/nginx/html

CMD [ "nginx", "-g", "daemon off;" ]
